In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/data-science-job-posting-on-glassdoor/Uncleaned_DS_jobs.csv
/kaggle/input/data-science-job-posting-on-glassdoor/Cleaned_DS_Jobs.csv

**OBJECTTICVE:**

`Clean and organize the data science job dataset scraped from WEB. Remove irrelevant data, handle missing values, and extract useful information to ensure consistency and better analysis.`

**DESCRIPTION :**

THIS DATASET IS ABOUT THE JOBS AVAIBALE AND INFORMATION REGARDING IT , LIKE WHAT IS THE SALARY RANGE OF THE JOB , BY WHICH COMPANY
IT IS POSTED , THIS DATASET ALSO HAS SOME RELATED INFORMTION ABOUT THE COMPANY

Total rows the data set has : (672)  and (15) attributes or columns 

**ATTRIBUTES**

['index', 'Job Title',/ 'Salary Estimate', 'Job Description', 'Rating', 'Company Name', 'Location', 'Headquarters','Size','Founded', 'Type of ownership', 'Industry', 'Sector','Revenue', 'Competitors']

**INFORMATION**

index : just a row number

Job Title : Job name example : Data Scientist

Salary Estimate : Salary range of the job  example: $137K-$171K (Glassdoor est.)

Job Description : Information about the role  

Rating : A floating number describing the importance of the role

Company Name : Orginization name which is offering the job

Location : Location of the company

Headquarter : Location  of headquarter

Size : Working force in the company

Founded:  Year of start of the company

Type of Ownership:  Telling either company is public private trust etc






Industry : area of working of company

Sector : Sector to which company belongs

Revenue : yearly money earn by company

Competitiors : Competitiors of the company

**PROBLEMS**

**DIRTY**


`Job description has \n in the text` :ACCURACY



`In company name there is \n , floating point digits , integers` : ACCURACY

`Headquarter has missing values as -1` : VALIDITY

`Rating of company is -1`  : VALIDITY


`Founded has missing values as -1` : VALIDITY

`Competitors has missing values as -1` : VALIDITY

`Replace Unknown / Non-Applicable with No Data in Revinew` : ACCURACY


`Convert the rating to smaller int like int8 or categorical` : ACCURACY

`Salary estimate has glass door etc remove it` : ACCURACY

`Job Entry has now Nans value repalce them With Any`

`Job Description has too dirty data see it `

**UNTIDY**
 

`Creata col of exp having roles like senior , experinced etc .. , junior would have No`

`Remove that Job exp from job title`

`Salary estimate : it has source of info attached to it seprate it` : 

`Company rating is mixed with the company name separate both columns`

In [3]:
data =  pd.read_csv('/kaggle/input/data-science-job-posting-on-glassdoor/Uncleaned_DS_jobs.csv')

In [6]:
data_Copy = data

In [54]:
data.sample(6)

Sr.
Senior
Jr

In [103]:
# Make a seprate column for  Role Entry 
import re
pattern = r'^(Senior|Sr\.?|Junior|Jr\.?)\s*'
exp  = data[data['Job Title'].str.contains(pattern)]
data['Role Entry'] = data['Job Title'].str.extract(pattern)

<ipython-input-103-3985c55c01a8>:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  exp  = data[data['Job Title'].str.contains(pattern)]

In [104]:
#Job title has Exp level hidden data , we have extract that data  , now remove that information from this column
data['Job Title'] = data['Job Title'].str.replace(pattern, '', regex=True)

In [125]:
#Data Descriptipn has \n in it , remove them
data['Job Description'] = data['Job Description'].apply(lambda x: x.replace('\n',''))

In [ ]:
temp = data['Salary Estimate'].str.split('(')
salary = temp.apply(lambda x : x[0])
source = temp.apply(lambda x:x[1])
data['Source'] = source.str.split(' ').apply(lambda x : x[0])
data['Salary Estimate'] = salary

In [165]:
data

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Role Entry,Source
0,0,Data Scientist,$137K-$171K,DescriptionThe Senior Data Scientist is respon...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NaN,Glassdoor
1,1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your FutureJoin the ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor
2,2,Data Scientist,$137K-$171K,OverviewAnalysis Group is one of the largest i...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,NaN,Glassdoor
3,3,Data Scientist,$137K-$171K,JOB DESCRIPTION:Do you have a passion for Data...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",NaN,Glassdoor
4,4,Data Scientist,$137K-$171K,Data ScientistAffinity Solutions / Marketing C...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NaN,Glassdoor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K,SummaryWeâ€™re looking for a data scientist to d...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,NaN,Glassdoor
668,668,Data Scientist,$105K-$167K,Job DescriptionBecome a thought leader within ...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor
669,669,Data Scientist,$105K-$167K,Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor
670,670,Data Scientist,$105K-$167K,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1,NaN,Glassdoor
671,671,Data Scientist,$105K-$167K,DescriptionThe Data Scientist will be part of ...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor

In [166]:
data

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Role Entry,Source
0,0,Data Scientist,$137K-$171K,DescriptionThe Senior Data Scientist is respon...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NaN,Glassdoor
1,1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your FutureJoin the ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor
2,2,Data Scientist,$137K-$171K,OverviewAnalysis Group is one of the largest i...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,NaN,Glassdoor
3,3,Data Scientist,$137K-$171K,JOB DESCRIPTION:Do you have a passion for Data...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",NaN,Glassdoor
4,4,Data Scientist,$137K-$171K,Data ScientistAffinity Solutions / Marketing C...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NaN,Glassdoor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K,SummaryWeâ€™re looking for a data scientist to d...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,NaN,Glassdoor
668,668,Data Scientist,$105K-$167K,Job DescriptionBecome a thought leader within ...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor
669,669,Data Scientist,$105K-$167K,Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor
670,670,Data Scientist,$105K-$167K,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1,NaN,Glassdoor
671,671,Data Scientist,$105K-$167K,DescriptionThe Data Scientist will be part of ...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor

In [202]:
#Make a seprate column f
def Setter(x):
    if len(x)==1:
        return None
    else:
        return x[1]
        
data['Rating OF Company'] = data['Company Name'].str.split('\n').apply(lambda x : Setter(x))

In [204]:
data.drop(columns =['Rating OF Company'])

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Role Entry,Source,Rating Of Company
0,0,Data Scientist,$137K-$171K,DescriptionThe Senior Data Scientist is respon...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NaN,Glassdoor,3.1
1,1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your FutureJoin the ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,4.2
2,2,Data Scientist,$137K-$171K,OverviewAnalysis Group is one of the largest i...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,NaN,Glassdoor,3.8
3,3,Data Scientist,$137K-$171K,JOB DESCRIPTION:Do you have a passion for Data...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",NaN,Glassdoor,3.5
4,4,Data Scientist,$137K-$171K,Data ScientistAffinity Solutions / Marketing C...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NaN,Glassdoor,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K,SummaryWeâ€™re looking for a data scientist to d...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,NaN,Glassdoor,3.6
668,668,Data Scientist,$105K-$167K,Job DescriptionBecome a thought leader within ...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
669,669,Data Scientist,$105K-$167K,Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
670,670,Data Scientist,$105K-$167K,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1,NaN,Glassdoor,5.0
671,671,Data Scientist,$105K-$167K,DescriptionThe Data Scientist will be part of ...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,2.7

In [208]:
#Changing the Company Name column with company name only 
data['Company Name']= data['Company Name'].str.split('\n').apply(lambda x: x[0])

In [230]:
data.drop(data.columns[-1], axis=1, inplace=True)
data.drop(data.columns[-1], axis=1, inplace=True)

In [231]:
data

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Role Entry,Source,Rating OF Company
0,0,Data Scientist,$137K-$171K,DescriptionThe Senior Data Scientist is respon...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",NaN,Glassdoor,3.1
1,1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your FutureJoin the ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,4.2
2,2,Data Scientist,$137K-$171K,OverviewAnalysis Group is one of the largest i...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,NaN,Glassdoor,3.8
3,3,Data Scientist,$137K-$171K,JOB DESCRIPTION:Do you have a passion for Data...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",NaN,Glassdoor,3.5
4,4,Data Scientist,$137K-$171K,Data ScientistAffinity Solutions / Marketing C...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",NaN,Glassdoor,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K,SummaryWeâ€™re looking for a data scientist to d...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,NaN,Glassdoor,3.6
668,668,Data Scientist,$105K-$167K,Job DescriptionBecome a thought leader within ...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
669,669,Data Scientist,$105K-$167K,Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
670,670,Data Scientist,$105K-$167K,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1,NaN,Glassdoor,5.0
671,671,Data Scientist,$105K-$167K,DescriptionThe Data Scientist will be part of ...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,2.7

In [237]:
data['Revenue'] = data['Revenue'].replace('Unknown / Non-Applicable',np.nan)

In [242]:
data.drop(columns = ['Rating'])

,index,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Role Entry,Source,Rating OF Company
0,0,Data Scientist,$137K-$171K,DescriptionThe Senior Data Scientist is respon...,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna",NaN,Glassdoor,3.1
1,1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your FutureJoin the ...",ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,4.2
2,2,Data Scientist,$137K-$171K,OverviewAnalysis Group is one of the largest i...,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,NaN,Glassdoor,3.8
3,3,Data Scientist,$137K-$171K,JOB DESCRIPTION:Do you have a passion for Data...,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",NaN,Glassdoor,3.5
4,4,Data Scientist,$137K-$171K,Data ScientistAffinity Solutions / Marketing C...,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee",NaN,Glassdoor,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K,SummaryWeâ€™re looking for a data scientist to d...,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,NaN,-1,NaN,Glassdoor,3.6
668,668,Data Scientist,$105K-$167K,Job DescriptionBecome a thought leader within ...,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
669,669,Data Scientist,$105K-$167K,Join a thriving company that is changing the w...,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
670,670,Data Scientist,$105K-$167K,100 Remote Opportunity As an AINLP Data Scient...,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1,NaN,Glassdoor,5.0
671,671,Data Scientist,$105K-$167K,DescriptionThe Data Scientist will be part of ...,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,2.7

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Role Entry,Source,Rating OF Company
0,0,Data Scientist,$137K-$171K,DescriptionThe Senior Data Scientist is respon...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna",NaN,Glassdoor,3.1
1,1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your FutureJoin the ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,4.2
2,2,Data Scientist,$137K-$171K,OverviewAnalysis Group is one of the largest i...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,NaN,Glassdoor,3.8
3,3,Data Scientist,$137K-$171K,JOB DESCRIPTION:Do you have a passion for Data...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",NaN,Glassdoor,3.5
4,4,Data Scientist,$137K-$171K,Data ScientistAffinity Solutions / Marketing C...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee",NaN,Glassdoor,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K,SummaryWeâ€™re looking for a data scientist to d...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,NaN,-1,NaN,Glassdoor,3.6
668,668,Data Scientist,$105K-$167K,Job DescriptionBecome a thought leader within ...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
669,669,Data Scientist,$105K-$167K,Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1,NaN,Glassdoor,None
670,670,Data Scientist,$105K-$167K,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1,NaN,Glassdoor,5.0
671,671,Data Scientist,$105K-$167K,DescriptionThe Data Scientist will be part of ...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1,NaN,Glassdoor,2.7

**FILLING THE MISSING VALUES**

DONT HAVE PROPER KNOWLEDGE ABOUT THE MISSING VALUES TECHNIQUES RIGHT NOW :

In [264]:
data['Rating']==-1
avg = np.round(data['Rating'].mean(),1)
data['Rating'] =data['Rating'].replace(-1 , avg)

In [281]:
data['Headquarters'] = data['Headquarters'].replace("-1",np.nan)

In [287]:

data['Size'] = data['Size'].replace("-1",np.nan)

In [292]:
data['Founded'] =data['Founded'].replace(-1,np.nan)

In [297]:
temp = data['Type of ownership'].value_counts().index[1]

data['Type of ownership'] = data['Type of ownership'].replace("-1",temp)

In [302]:
data[['Industry', 'Sector','Revenue','Competitors']] = data[['Industry', 'Sector','Revenue','Competitors']].replace("-1", np.nan)

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Role Entry,Source,Rating OF Company
0,0,Data Scientist,$137K-$171K,DescriptionThe Senior Data Scientist is respon...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993.0,Nonprofit Organization,Insurance Carriers,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna",NaN,Glassdoor,3.099609
1,1,Data Scientist,$137K-$171K,"Secure our Nation, Ignite your FutureJoin the ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968.0,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),NaN,NaN,Glassdoor,4.199219
2,2,Data Scientist,$137K-$171K,OverviewAnalysis Group is one of the largest i...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981.0,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),NaN,NaN,Glassdoor,3.800781
3,3,Data Scientist,$137K-$171K,JOB DESCRIPTION:Do you have a passion for Data...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000.0,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",NaN,Glassdoor,3.500000
4,4,Data Scientist,$137K-$171K,Data ScientistAffinity Solutions / Marketing C...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998.0,Company - Private,Advertising & Marketing,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee",NaN,Glassdoor,2.900391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K,SummaryWeâ€™re looking for a data scientist to d...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989.0,Company - Private,Advertising & Marketing,Business Services,NaN,NaN,NaN,Glassdoor,3.599609
668,668,Data Scientist,$105K-$167K,Job DescriptionBecome a thought leader within ...,3.5,JKGT,"San Francisco, CA",NaN,NaN,NaN,Company - Public,NaN,NaN,NaN,NaN,NaN,Glassdoor,NaN
669,669,Data Scientist,$105K-$167K,Join a thriving company that is changing the w...,3.5,AccessHope,"Irwindale, CA",NaN,NaN,NaN,Company - Public,NaN,NaN,NaN,NaN,NaN,Glassdoor,NaN
670,670,Data Scientist,$105K-$167K,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,NaN,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),NaN,NaN,Glassdoor,5.000000
671,671,Data Scientist,$105K-$167K,DescriptionThe Data Scientist will be part of ...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976.0,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),NaN,NaN,Glassdoor,2.699219